language: node_js

node_js:
  - '4'

cache:
  directories:
    - node_modules

before_install:

install:
  - npm install

before_script:
  - npm install -g gulp

script:
  - gulp clean

branches:
 only:
  - master